angular.module('tombola.noughtsAndCrossesApp.service',[]);
    angular.module('tombola.noughtsAndCrossesApp.directive',[]);
        angular.module('tombola.noughtsAndCrossesApp.controllers',[]);
            angular.module('tombola.noughtsAndCrossesApp.filter',[]);
                angular.module('tombola.noughtsAndCrossesApp',[
                'tombola.noughtsAndCrossesApp.service',
                'tombola.noughtsAndCrossesApp.directive',
                'tombola.noughtsAndCrossesApp.controllers',
                'tombola.noughtsAndCrossesApp.filter'
]);
